/**
 * Creates a document via `Model.create(buildDoc())`, rebuilding it and
 * retrying on a duplicate-key error (Mongo code 11000) instead of trusting a
 * `count()`-then-insert check, which has a race window under concurrent
 * requests. Only retries when the number was auto-generated — a
 * user-supplied number that collides should fail loudly, not be silently
 * replaced.
 */
export const createWithUniqueNumber = async (Model, buildDoc, wasAutoGenerated, attempts = 5) => {
  for (let i = 0; i < attempts; i++) {
    try {
      return await Model.create(buildDoc());
    } catch (err) {
      const isDuplicateNumber = err.code === 11000 && wasAutoGenerated;
      if (!isDuplicateNumber || i === attempts - 1) throw err;
      // fall through and retry with a freshly built (re-numbered) doc
    }
  }
};
